---
# file: /etc/datawire/watson.yml.example
#
# An example Datawire Watson configuration file.

sherlock:
  service_registry:
    host: localhost
    port: 52689
    #token: <%= ENV['REGISTRY_SECURITY_TOKEN'] %>

  haproxy:
    executable: /bin/haproxy
    config_dir: /opt/datawire/bakerstreet/run
    command:

  debounce: 5

watson:

#  Replacement Syntax for the service_registry: String field
#
#  service_registry:
#    host: localhost
#    port: 52689
#    token: <%= ENV['REGISTRY_SECURITY_TOKEN'] %>

  service_registry: localhost:52689
  service:
    # the name of the service
    name: foobar-service

    # the url of the service
    url: http://localhost:2218
  health_check:
    # the type of health check (currently only 'http' is supported)
    type: http

    # the health check method
    method: GET

    # the url of the health check (can be http or https)
    url: http://localhost:2218/health

    # the frequency of the health check
    frequency: 1s

    # HTTP statuses that should be considered healthy.
    healthy_statuses:
      - 200
      - 204

    # timeout period after which a service will be marked as unhealthy
    timeout: 5s

    # the number of consecutive failed checks before the service is marked as unhealthy.
    unhealthy_threshold: 3

    # the number of consecutive successful checks before the service is marked as healthy.
    healthy_threshold: 3
  logging:
    format: "-->  %(levelname)s: %(name)s - %(asctime)s - %(message)s"
    level: info
